---
- name: Retrieve MicWilliStores service ID from DWP
  hosts: localhost
  gather_facts: false
  vars:
    dwp_base_url: "https://helixdemoash626-demo-dwp.onbmc.com/dwp/rest"
    username: "Liam"
    password: "Password_1234"
    target_service_name: "MicWilliStores"

  tasks:
    - name: Login to DWP and get session cookie
      ansible.builtin.uri:
        url: "{{ dwp_base_url }}/users/sessions/login"
        method: POST
        headers:
          X-Requested-By: "XMLHttpRequest"
          Content-Type: "application/json; charset=UTF-8"
        body_format: json
        body:
          loginId: "{{ username }}"
          password: "{{ password }}"
          appName: "dwp"
          apiVersion: 19020000
          locale: "en-US"
          deviceToken: "dummyToken"
          os: "Windows 10"
          model: "Web Client"
        return_content: yes
        status_code: 200
      register: login_response

    - name: Extract DWP session cookie
      set_fact:
        dwp_cookie_header: "{{ login_response.cookies | dict2items | first.key ~ '=' ~ login_response.cookies[login_response.cookies | dict2items | first.key] }}"

    - name: Query MYIT_ALL_SERVICES
      ansible.builtin.uri:
        url: "{{ dwp_base_url }}/search"
        method: POST
        headers:
          X-Requested-By: "XMLHttpRequest"
          Content-Type: "application/json; charset=UTF-8"
          Cookie: "{{ dwp_cookie_header }}"
        body_format: json
        body:
          queryName: "MYIT_ALL_SERVICES"
          attributes:
            ServiceAvailability:
              - id
              - linkedServiceId
              - linkedServiceName
              - name
              - annotation
              - status
              - externalStatus
              - isEnabled
              - statusIsManual
        return_content: yes
        status_code: 200
      register: services_response

    - name: Parse JSON response
      set_fact:
        services_list: "{{ services_response.json.items }}"

    - name: Find MicWilliStores service
      set_fact:
        micwilli_service_id: "{{ services_list | selectattr('name','equalto', target_service_name) | map(attribute='id') | first }}"

    - name: Show MicWilliStores service ID
      ansible.builtin.debug:
        msg: "Service ID for {{ target_service_name }} is {{ micwilli_service_id }}"