---
- name: Mark a DWP service as unavailable
  hosts: localhost
  gather_facts: false
  vars:
    dwp_url: "https://helixdemoash626-demo-dwp.onbmc.com/dwp/rest"
    login_payload:
      loginId: "Liam"
      password: "Password_1234"
      appName: "dwp"
      apiVersion: 19020000
      locale: "en-US"
      deviceToken: "dummyToken"
      os: "Windows 10"
      model: "Web Client"
    target_service_name: "MicWilliStores"

  tasks:
    - name: Login to DWP and store cookies
      ansible.builtin.shell: >
        curl -s -c cookies.txt -H 'X-Requested-By: XMLHttpRequest'
        -H 'Content-Type: application/json; charset=UTF-8'
        -X POST "{{ dwp_url }}/users/sessions/login"
        -d '{{ login_payload | to_json }}'
      register: login_response
      changed_when: false

    - name: Ensure login was successful
      assert:
        that:
          - '"HTTP/1.1 200" in login_response.stdout'
        fail_msg: "Login failed. Check credentials or DWP endpoint."

    - name: Query MYIT_ALL_SERVICES
      ansible.builtin.shell: >
        curl -s -b cookies.txt -H 'X-Requested-By: XMLHttpRequest'
        -H 'Content-Type: application/json; charset=UTF-8'
        -X POST "{{ dwp_url }}/search"
        -d '{
              "queryName": "MYIT_ALL_SERVICES",
              "attributes": {
                "ServiceAvailability": [
                  "id", "linkedServiceId", "linkedServiceName", "name", 
                  "annotation", "status", "externalStatus", "isEnabled", "statusIsManual"
                ]
              }
            }'
      register: services_response
      changed_when: false

    - name: Parse JSON response
      set_fact:
        services_list: "{{ services_response.stdout | from_json }}"

    - name: Find target service ID
      set_fact:
        target_service_id: "{{ services_list | selectattr('name','equalto', target_service_name) | map(attribute='id') | first | default(None) }}"

    - name: Fail if target service not found
      fail:
        msg: "Target service '{{ target_service_name }}' not found in MYIT_ALL_SERVICES."
      when: target_service_id is none

    - name: Display the target service ID
      debug:
        msg: "Target service ID for '{{ target_service_name }}' is {{ target_service_id }}"