- name: Login to DWP and get token
  ansible.builtin.uri:
    url: https://helixdemoash626-demo-dwp.onbmc.com/dwp/rest/users/sessions/login
    method: POST
    headers:
      X-Requested-By: Ansible
      Content-Type: application/json
    body: |
      {
        "loginId": "Liam",
        "password": "Password_1234",
        "appName": "dwp",
        "apiVersion": 19020000,
        "locale": "en-US",
        "deviceToken": "dummyToken",
        "os": "Windows 10",
        "model": "Web Client"
      }
    body_format: json
    return_content: yes
  register: login_response

- name: Store AR-JWT token
  set_fact:
    ar_jwt_token: "{{ login_response.json.token }}"

- name: Query MYIT_ALL_SERVICES with token
  ansible.builtin.uri:
    url: https://helixdemoash626-demo-dwp.onbmc.com/dwp/rest/search
    method: POST
    headers:
      X-Requested-By: Ansible
      Content-Type: application/json
      Authorization: "AR-JWT {{ ar_jwt_token }}"
    body: |
      {
        "queryName": "MYIT_ALL_SERVICES",
        "attributes": {
          "ServiceAvailability": ["id", "name", "status"]
        }
      }
    body_format: json
    return_content: yes
  register: search_response