---
- name: Update availability of MicWilliStores service
  hosts: localhost
  gather_facts: false
  vars:
    base_url: "https://helixdemoash626-demo-dwp.onbmc.com/dwp/rest"
    username: "Liam"
    password: "Password_1234"
    target_service_name: "MicWilliStores"

  tasks:

    - name: Get all ServiceAvailability entries
      ansible.builtin.uri:
        url: "{{ base_url }}/update"
        method: GET
        user: "{{ username }}"
        password: "{{ password }}"
        force_basic_auth: yes
        headers:
          X-Requested-By: XMLHttpRequest
        return_content: yes
        status_code: 200
      register: all_services

    - name: Parse JSON to find target service
      ansible.builtin.set_fact:
        target_service: "{{ (all_services.json | selectattr('name','equalto', target_service_name) | list)[0] }}"
      failed_when: target_service is not defined

    - name: Show ID of the target service
      ansible.builtin.debug:
        msg: "Found service '{{ target_service_name }}' with ID {{ target_service.id }}"

    - name: Update the availability of the target service to 10
      ansible.builtin.uri:
        url: "{{ base_url }}/update"
        method: POST
        user: "{{ username }}"
        password: "{{ password }}"
        force_basic_auth: yes
        headers:
          X-Requested-By: XMLHttpRequest
          Content-Type: "application/json; charset=UTF-8"
        body_format: json
        body:
          ServiceAvailability:
            id: "{{ target_service.id }}"
            changes:
              status: 10
        status_code: 200
        return_content: yes
      register: update_result

    - name: Show update response
      ansible.builtin.debug:
        var: update_result.content