- name: Update Windows Service By Name and State
  hosts: {{ TargetHost }}
  gather_facts: no
  tasks:
    - name: Update Windows Service by State
      ansible.windows.win_service:
        name: {{ WindowsServiceName }}
        state: {{ ServiceState }}